// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gDHRk9XBeh3VImqSi7ozOWRPsMAVsy8',
    appId: '1:307102848946:web:cba2ebf0e4d251187b76ab',
    messagingSenderId: '307102848946',
    projectId: 'dbhakim-82cbd',
    authDomain: 'dbhakim-82cbd.firebaseapp.com',
    storageBucket: 'dbhakim-82cbd.appspot.com',
    measurementId: 'G-1ZVE7RTTB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVwcTagiXKHw50OQ3_jrqctWwWuHmvv1s',
    appId: '1:307102848946:android:95bcee2db39f3ac67b76ab',
    messagingSenderId: '307102848946',
    projectId: 'dbhakim-82cbd',
    storageBucket: 'dbhakim-82cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArG760OymC5k75Bp2Bo1wiFE6xwk0_B7w',
    appId: '1:307102848946:ios:c677142900e47f507b76ab',
    messagingSenderId: '307102848946',
    projectId: 'dbhakim-82cbd',
    storageBucket: 'dbhakim-82cbd.appspot.com',
    iosClientId: '307102848946-908orvgda4neltqn3jiqd5n526vjn7cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hakimTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArG760OymC5k75Bp2Bo1wiFE6xwk0_B7w',
    appId: '1:307102848946:ios:c677142900e47f507b76ab',
    messagingSenderId: '307102848946',
    projectId: 'dbhakim-82cbd',
    storageBucket: 'dbhakim-82cbd.appspot.com',
    iosClientId: '307102848946-908orvgda4neltqn3jiqd5n526vjn7cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hakimTravel',
  );
}
